---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bump-api
  namespace: web
  labels:
    name: bump-api
    app: bump-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bump-api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7070"
      labels:
        app: bump-api
    spec:
      containers:
      - name: bump-api
        image: saidsef/bump-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
        livenessProbe:
          exec:
            command:
              - pgrep
              - python
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 7070
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"