---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bump-api
  labels:
    app.kubernetes.io/name: bump-api
    app.kubernetes.io/instance: bump-api
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: bump-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bump-api
      annotations:
        prometheus.io/scrape: "true"
        filter.by.port.name: "true"
    spec:
      restartPolicy: Always
      securityContext:
        runAsGroup: 65534
        runAsUser: 65534
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bump-api
          image: docker.io/saidsef/bump-api:v2023.02
          imagePullPolicy: Always
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 7070
              protocol: TCP
              name: http
          livenessProbe:
            exec:
              command:
                - pgrep
                - python
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 7070
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              subPath: tmp
              readOnly: false
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1Gi
