---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bump-api
  namespace: web
  labels:
    name: bump-api
    app: bump-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bump-api
  template:
    metadata:
      labels:
        app: bump-api
    spec:
      containers:
      - name: bump-api
        image: saidsef/bump-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070


