---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

vars:
- fieldref: {}
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: bump-api
