---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

images:
  - name: bump-api
    newName: docker.io/saidsef/bump-api
    newTag: v2023.02

commonAnnotations:
  app.kubernetes.io/managed-by: kustomizer

vars:
- fieldref: {}
  name: HOST
  objref:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: bump-api
