---
apiVersion: v1
kind: Service
metadata:
  name: bump-api
  namespace: web
  labels:
    app: bump-api
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: bump-api
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
    name: web