---
apiVersion: v1
kind: Service
metadata:
  name: bump-api
  namespace: web
  labels:
    app: bump-api
    tier: frontend
  annotations:
    prometheus.io/port: "7070"
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  selector:
    app: bump-api
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
    name: web